helsingborg-stad/mitt-helsingborg-form-builder

src/components/specific/Questions/QuestionField.tsx
Add a show sum option to summary list input
=> Add a show sum option to summary list input

src/components/specific/Questions/QuestionField.tsx
Add option for SummaryList to start in editable mode or not. Default is false.
=> Add option for SummaryList to start in editable mode or not

src/components/specific/Questions/QuestionField.tsx, src/components/specific/Questions/SelectChoice.tsx
Add the select (dropdown menu) as an option for input fields, and adds the required options.
=> add select as an option for input field

src/components/specific/Questions/QuestionField.tsx, src/components/specific/Questions/ValidationRules.ts
Add option to control if the editable list starts in edit mode or not. 
Some minor fixes to validation rule texts as well.
=> Add option for editable list to start editable

src/components/general/SubContainer.tsx, src/components/specific/StepList/StepList.tsx, src/components/specific/Steps/StepField.tsx, src/helpers/object.ts
Fix so that you don't deselect current step when clicking on a selected step, as it made the UX feel clunky. And some minor cleanup of unused code.
=> Change click behavior in stepList

.github/workflows/develop.yml
Add a github action to deploy pushes to the develop branch to an AWS S3 bucket, for continuous deployment.
=> add a deploy action to the develop branch

src/preview/components/Button/Button.js, src/preview/components/FormField/FormField.js, src/preview/components/NavigationButtonGroup/NavigationButtonGroup.tsx
Adds navigation button group preview functionality.
=> add NavigationButtonGroup to preview

src/preview/components/Button/Button.js, src/preview/components/NavigationButtonGroup/NavigationButtonGroup.tsx, src/preview/styles/themeHelpers.ts
Hotfix for a nasty bug which would crash if the user put in an invalid color for navigation buttons
=> fix a bug with wrong colors crashing the app

src/components/specific/Steps/ActionField.tsx
add new navigation action: backToMainAndNext
=> add new navigation action: backToMainAndNext

src/components/specific/Steps/ActionField.tsx, src/types/FormTypes.ts
Adds conditions to the ActionField, and fixes some form types.
=> feat(action-conditions): add option to add conditions to actions

src/components/specific/Questions/QuestionField.tsx, src/preview/components/FormField/FormField.js, src/preview/components/ImageDisplay/ImageDisplay.tsx, src/preview/components/ImageDisplay/ImageItem.tsx, src/preview/components/ImageUploader/ImageUploader.tsx, src/preview/components/ImageViewer/ImageViewer.tsx, src/types/FieldDescriptor.ts
Refactor ImageUploader to match the refactor in the app.
=> feat(image-viewer): add imageViewer to preview. 

src/components/specific/FormDataField.tsx
=> feat(ekb-completion-form-type): add option for EKB-completion form 

README.md
update the readme with a small technical overview
=> fix(readme): update the readme with a small technical overview

src/components/general/SmartInputs/LoadPreviousToggle.tsx, src/types/UserType.ts
Added option to select load previous data from co-applicant.
=> feat: select to load previous data from co applicant

src/components/specific/Questions/QuestionField.tsx, src/preview/components/BulletList/BulletList.tsx, src/preview/components/FormField/FormField.js, src/types/FieldDescriptor.ts
Created a new components that lets the application displays values in a bullet list
Solved it by creating the new component from scratch. The component takes values as a string array and optionally a colorSchema value for colouring the background and the bullets in the bullet list.
This is how other components are added in the form builder. The component is also independently added in the form which means that it will not break any other functionality. 
Created a form with the new component and checked the data structure that the form created.
=> feat: add bullet list as a new component in form builder

src/components/specific/Questions/InputTypes/CheckboxListChoice.tsx, src/components/specific/Questions/QuestionField.tsx, src/preview/components/CheckboxField/CheckboxField.tsx, src/preview/components/CheckboxList/CheckboxList.tsx, src/preview/components/FormField/FormField.js, src/types/FieldDescriptor.ts
Adds a new checkbox list component according to #CU-234a8f5
=> ✨ Add checkbox list as a field type

src/components/specific/Questions/QuestionField.tsx, src/types/FieldDescriptor.ts
* Added "fileUploaderList" component
* Changed answers in bulletList to initialValues for consistency and to avoid key collision in frontend (requires [PR 695 from app](https://github.com/helsingborg-stad/app-mitt-helsingborg/pull/695))
=> feat: add file uploader list

src/components/specific/Questions/QuestionField.tsx, src/helpers/fileTypes.ts, src/preview/components/FilePicker/FilePicker.styled.ts, src/preview/components/FilePicker/FilePicker.tsx, src/preview/components/FormField/FormField.js, src/types/FieldDescriptor.ts
**What was done**
Added new component (filepicker) for uploading both images and pdf:s in the same component
**How was it done**
Added the new component type as other components are added in formbuilder.
**Why was it done in this way**
This is how its done
**How was it tested**
Changed a form that uses the new component and tested it in the application
=> feat: add new file picker component

src/components/specific/Questions/QuestionField.tsx, src/preview/components/FileDisplay/FileDisplay.styled.ts, src/preview/components/FileDisplay/FileDisplay.tsx, src/preview/components/FileItem/FileItem.styled.ts, src/preview/components/FileItem/FileItem.tsx, src/preview/components/FileViewer/FileViewer.styled.ts, src/preview/components/FileViewer/FileViewer.tsx, src/preview/components/FormField/FormField.js, src/types/FieldDescriptor.ts
**What was done**
Added new fileviewer components which is going to be used to display files (images and pdfs) added by a user in the form.
**How was it done**
Took inspiration from the other Xviewer components and created new files for the fileviewer. 
**Why was it done in this way**
This is how its done for the other Xviewer components
**How was it tested**
Created a form with the FileViewer component and tried it out in the application.
=> feat: add fileviewer component

src/components/specific/Questions/QuestionField.tsx, src/components/specific/Questions/ValidationRules.ts
**What was done**
Add the possibility to make filepicker a required question in the form
**How was it done**
Added a required rule to the component
**Why was it done in this way**
This is how its done
**How was it tested**
Implemented the functionality and tested the property in the application.
Updated the application to be compatible with the new property
=> fix(filepicker): add required property to filepicker

src/components/specific/Questions/QuestionField.tsx
Add tags fields to radio-group (Radio Buttons).
=> feat(radio-group): add tags field
